### ISSUE TITLE
Edit Option is not working in CRUD operation

### ISSUE THREAD

**Issue by vpenugonda** [vpenugonda/expensetracker#1]
When the user clicked on EDIT option, that should populate the values to the Form which is on the left side of the screen.

Please feel free to ask if any questions.

**Comment by omjego** [comment]
So you already implemented it and it's not working or you want add this new feature altogether ?

**Comment by vpenugonda** [comment]
I figured out the way to implement the update option.. i have to push the code.. 
Thanks for your time.
